First homework
daemonicat/AQA_MTS_Learn pull request #1
Opened 2023-11-18 08:58 UTC by daemonicat

2023-11-20 21:05 UTC, wildpioneer requested changes

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/FirstTask.cs
> +        try
Мы еще не изучали try - catch блоки ;) - но я понял что ты их знаешь

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/FirstTask.cs
> +        if (emptyInput) return;
Хм - а почему сразу не выполнять return не используя этот emptyInput?

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/FirstTask.cs
> +                Console.WriteLine(result);
Дублирование кода - нужно было вынести вывод после switch-case

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/FirstTask.cs
> +    public static void Main(){
Фигурная скобка должны быть с новой строки

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/FirstTask.cs
> +        if (string.IsNullOrEmpty(operationSign))
Мы еще не знаем операция со строками - но я понял что ты знаком

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/FourthTask.cs
> +        if (emptyInput) return;
Опять та же логическая ошибка - не стоит продолжать выполнение если произошел exception

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/SecondTask.cs
> +        switch (inputNumber)
Отсутствует проверка что введенное число в диапазоне от -50 до +50

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/SecondTask.cs
> +        float inputNumber = 0;
Не надо задавать начальное значение - потому как ты его в любом случае читаешь с консоли

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/ThirdTask.cs
> +        if (emptyInput) return;
Опять эта ошибка

2023-11-20 21:05 UTC, wildpioneer commented on typesAndOperators/ThirdTask.cs
> +        switch (weatherWord)
Перед switch необходимо вставить пустую строку

2023-11-20 21:37 UTC, daemonicat commented on typesAndOperators/FirstTask.cs
> +        try
Это я в целом вспоминал, как нужно оформлять ввод, могу не использовать в дальнейшем :)

2023-11-20 21:38 UTC, daemonicat commented on typesAndOperators/FirstTask.cs
> +        if (emptyInput) return;
Тут я сначала написал без try-catch, в итоге так и осталось, перенесу

2023-11-20 21:41 UTC, daemonicat commented on typesAndOperators/SecondTask.cs
> +        switch (inputNumber)
А её здесь нужно разве в явном виде проводить? Промежуток, в котором мы выполняем поиск – [-40;40], по этому условию уже не важно, входит число в промежуток [-50;50]

2023-11-20 21:57 UTC, wildpioneer commented on typesAndOperators/SecondTask.cs
> +        switch (inputNumber)
У нас в условии задачи говориться что вводиться число от -50 до 50 - а это и есть условие

2023-11-21 11:49 UTC, daemonicat commented on typesAndOperators/SecondTask.cs
> +        switch (inputNumber)
Добавил проверку на диапазон введённого числа

2023-11-27 17:03 UTC, closed without merging