Arrays hw
daemonicat/AQA_MTS_Learn pull request #2
Opened 2023-11-21 15:17 UTC by daemonicat

1-4 tasks + 8 task

2023-11-27 17:22 UTC, wildpioneer requested changes

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/FirstTask.cs
> +        try
Нужна пустая строка для более комфортного чтения кода

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/FirstTask.cs
> +            inputNumber = int.Parse(inputNumberStr);
В идеале лучше реализовать ввод в виде цикла - пока не будет введено верно. Но это опять же спорный вопрос

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/FirstTask.cs
> +            Console.WriteLine(e.Message);
Чистый exception мне ни о чем ни скажет - лучше выводить понятное сообщение.

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/FirstTask.cs
> +        foreach (var item in array)
Опять же - если говорить об эффективности - то цикл foreach пройдет по всем элементам. А зачем нам идти по всем, если скажем уже на первом элементе понятно что введенное число входит в массив?
Разумнее использовать do-while цикл

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/SecondTask.cs
> +        Console.Write("Enter your number: ");
А как пользователь узнает какие цифры есть в массиве? Нужно организовать вывод - чтобы не гадать.

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/SecondTask.cs
> +        try
Пустая строка нужна

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/SecondTask.cs
> +        array = array.Where(num => num != inputNumber).ToArray();
Технически верно, но логически не совсем. Ты изменил существующий массив, а в задании говориться о создании нового. Ну и вывод результата выполнения хотелось бы увидеть.

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/ThirdTask.cs
> +        Console.Write("Enter your number: ");
Этот блок - такие комментарии как и к первому заданию

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/ThirdTask.cs
> +            Console.Write($"{array[i]} ");
Про эффективность - а почему эти две строки кода не делать сразу после инициализации значения в строке 23? Получается что два этих цикла можно смержить в один.

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/ThirdTask.cs
> +        Console.WriteLine($"Average value is {sum / (array.GetUpperBound(0) + 1)}");
Это ты мне вывел среднее арифметическое - а надо просто среднее
1 5 10
Среднее = 5
Среднее арифметическое  = 5.3

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/FourthTask.cs
> +            if (i == array.GetUpperBound(0)) Console.WriteLine();
Я так понимаю, что такой подход был с прицелом на двухмерные массивы - но тогда и реализовываться он должен немного по другому. А для одноименного - зачем такое количество проверок IF? Достаточно одного Console.WriteLine() после цикла.

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/FourthTask.cs
> +        for (int i = 0; i <= array.GetUpperBound(0); i++)
1. Пустая строка перед for нужна
2. А если у тебя массивы будут разной длинны?

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/FourthTask.cs
> +        if (sum / 5 > sum1 / 5)
1. Не ну это совсем уже детский вариант. Давай как использовать деление на длину массива.
2. Расчет средних нужно вынести в переменные и произвести до IF-ов

2023-11-27 17:22 UTC, wildpioneer commented on Arrays/EightTask.cs
> +        for (int i = 0; i <= array.GetUpperBound(0); i++)
Комментарий по выводу такой же как и для всех остальных задач.

2023-11-27 17:40 UTC, daemonicat commented on Arrays/ThirdTask.cs
> +        Console.WriteLine($"Average value is {sum / (array.GetUpperBound(0) + 1)}");
Какое число считать средним в случае, когда в массиве чётное кол-во элементов? { 1, 2, 3, 4 } - правильный ответ 2 или 3? Или нужно выводить ошибку в таком кейсе?

2023-11-27 17:42 UTC, daemonicat commented on Arrays/FourthTask.cs
> +        for (int i = 0; i <= array.GetUpperBound(0); i++)
2. Создайте 2 массива из 5 чисел.
Согласно заданию, такого кейса не будет. Было бы условие "Создайте 2 массива разной длины" - реализация была бы другой

2023-11-27 17:43 UTC, daemonicat commented on Arrays/FourthTask.cs
> +        if (sum / 5 > sum1 / 5)
1. Окей, но тут всё ещё работает отговорка "ТЗ такое"

2023-11-27 18:26 UTC, daemonicat commented on Arrays/FourthTask.cs
> +        if (sum / 5 > sum1 / 5)
2. А в чём смысл их выносить в отдельные переменные? Покрутил в голове, но так и не понял

2023-11-27 18:30 UTC, daemonicat commented on Arrays/FirstTask.cs
> +            Console.WriteLine(e.Message);
Поправил, но, справедливости ради, это сообщение выглядит так:
The input string '' was not in a correct format.
Думал, это достаточно информативно

2023-12-04 13:15 UTC, wildpioneer commented on Arrays/FourthTask.cs
> +        if (sum / 5 > sum1 / 5)
Смысл в том - что ты используешь это выражение несколько раз - а следовательно это переменные. Если бы только 1 раз - то тогда без проблем - выражение

2023-12-04 13:15 UTC, wildpioneer commented
Проверено

2023-12-04 13:15 UTC, closed without merging